[general]
nick = "maxedIRC"
username = "maxedIRC"
realname = "maxed irc client"
theme = "default"
timestamp_format = "%H:%M:%S"
flood_protection = true
ctcp_version = "kokoIRC — koko maxed irc client"

[display]
nick_column_width = 8
nick_max_length = 8
nick_alignment = "right"
nick_truncation = true
show_timestamps = true
scrollback_lines = 2000

[sidepanel.left]
width = 14
visible = true

[sidepanel.right]
width = 14
visible = true

[statusbar]
enabled = true
items = [ "time", "nick_info", "channel_info", "lag", "active_windows" ]
separator = " | "
prompt = "[$server❱ "

[servers.ircnet]
label = "IRCnet"
address = "sasl.irc.atw.hu"
port = 6697
tls = true
autoconnect = true
channels = [ "#sqrwiele", "#dupai" ]
sasl_user = "kofany"

[aliases]
wc = "/close"
