[general]
nick = "kofany_tui"
username = "kofany"
realname = "OpenTUI IRC"
theme = "default"
timestamp_format = "%H:%M:%S"

[display]
nick_column_width = 8
nick_max_length = 8
nick_alignment = "right"
nick_truncation = true
show_timestamps = true
scrollback_lines = 2000

[sidepanel.left]
width = 20
visible = true

[sidepanel.right]
width = 18
visible = true

[servers.ircnet]
label = "IRCnet"
address = "sasl.irc.atw.hu"
port = 6697
tls = true
autoconnect = true
channels = ["#polska", "#tahio"]
